name: Build and Push Eagapps Image
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eagapps
  PYTHON_VERSION: 3.14

jobs:
  push:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Setup app.json
        run: |
          cat > apps.json <<EOF
          [
            {
              "url": "${{ secrets.EAGAPPS_URL }}",
              "branch": "${{ secrets.EAGAPPS_BRANCH }}"
            }
          ]
          EOF
          mv apps.json ./frappe_docker/apps.json

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./frappe_docker
          file: ./frappe_docker/images/custom/Containerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            FRAPPE_PATH: https://github.com/frappe/frappe
            FRAPPE_BRANCH: version-16
            PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
          secrets-files: |
            apps_json=apps.json

      - name: Remove apps.json
        if: "${{ always() }}"
        run: rm ./frappe_docker/apps.json
